/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.avbravo.nbdbdump;

import java.io.IOException;
import java.util.MissingResourceException;
import java.util.prefs.PreferenceChangeEvent;
import java.util.prefs.PreferenceChangeListener;
import java.util.prefs.Preferences;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.awt.ActionID;
import org.openide.util.NbBundle;
import org.openide.util.NbBundle.Messages;
import org.openide.util.NbPreferences;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//org.avbravo.nbdbdump//nbdbdump//EN",
        autostore = false)
//@TopComponent.Description(preferredID = "NbDbDumpDialog",
//        iconBase = "org/avbravo/nbdbdump/restoredb.png",
//        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
//@TopComponent.Registration(mode = "commonpalette", openAtStartup = false)
@ActionID(category = "Database", id = "org.avbravo.nbdbdump.nbdbdumpTopComponent")
//@ActionReference(path = "Menu/Window" /*
// * , position = 333
// */)
//@TopComponent.OpenActionRegistration(displayName = "#CTL_nbdbdumpAction",
//        preferredID = "NbDbDumpDialog")
@Messages({
    "CTL_nbdbdumpAction=nbdbdump",
    "CTL_nbdbdumpTopComponent=nbdbdump Window",
    "HINT_nbdbdumpTopComponent=This is a nbdbdump window"
})
public final class NbDbDumpDialog extends JDialog {
    NotifyDescriptor nd;
    String archivoBackup = "";
    String rutaBackup = "";
    String archivoRestore = "";
    String rutaRestore = "";
    String dataBase = "";
    String host = "";
    String separadorSO = System.getProperties().getProperty("file.separator");
    Integer Anio, Mes, Dia, hours, min, seconds;
    String osName = System.getProperty("os.name").toLowerCase();

    public NbDbDumpDialog() {
        initComponents();
//        setName(Bundle.CTL_nbdbdumpTopComponent());
//        setToolTipText(Bundle.HINT_nbdbdumpTopComponent());
        try {
//            DatabaseExplorerUIs.connect(dataBasesComboBox, ConnectionManager.getDefault());

            Preferences pref = NbPreferences.forModule(NbDbDumpOptionsPanel.class);
            String name = pref.get("pathmysql", "");
            //String pathBackupFolder = pref.get("pathbackupfolder", "");
            //jTextFieldRuta.setText(pathBackupFolder);
//            jLabelMySQLPath.setText(name);
            pref.addPreferenceChangeListener(new PreferenceChangeListener() {

//            public void preferenceChange(PreferenceChangeEvent evt) {
//
//            }
                @Override
                public void preferenceChange(PreferenceChangeEvent evt) {
                    if (evt.getKey().equals("pathmysql")) {
//                        jLabelMySQLPath.setText(evt.getNewValue());
                    }
                }
            });

        } catch (Exception e) {
            error(e.getLocalizedMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldRuta = new javax.swing.JTextField();
        jButtonSelectDirectory = new javax.swing.JButton();
        dataToFilenameCheckbox = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButtonCargar = new javax.swing.JButton();
        jButtonRestore = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabelRutaBackup = new javax.swing.JLabel();
        jLabelArchivoBackup = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldComando = new javax.swing.JTextField();
        mysqldumpPathLabel = new javax.swing.JLabel();
        mysqldumpPathBtn = new javax.swing.JButton();
        mysqldumpPathTextField = new javax.swing.JTextField();
        statementsComboBox = new javax.swing.JComboBox<String>();
        selectedDatabasesTextField = new javax.swing.JTextField();
        statementsLabel = new javax.swing.JLabel();
        selectedDatabasesLabel = new javax.swing.JLabel();
        okBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldPathMongodb = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButtonSelectDirectory1 = new javax.swing.JButton();
        jButtonBackup1 = new javax.swing.JButton();
        jButtonRestore1 = new javax.swing.JButton();
        jButtonSelectDirectory2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jTextFieldRuta.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jTextFieldRuta.setText(org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jTextFieldRuta.text")); // NOI18N
        jTextFieldRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRutaActionPerformed(evt);
            }
        });

        jButtonSelectDirectory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/nbdbdump/resources/open-icon.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButtonSelectDirectory, org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jButtonSelectDirectory.text")); // NOI18N
        jButtonSelectDirectory.setToolTipText(org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jButtonSelectDirectory.toolTipText")); // NOI18N
        jButtonSelectDirectory.setEnabled(false);
        jButtonSelectDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectDirectoryActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(dataToFilenameCheckbox, org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.dataToFilenameCheckbox.text")); // NOI18N
        dataToFilenameCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataToFilenameCheckboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonSelectDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dataToFilenameCheckbox))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSelectDirectory)
                    .addComponent(jTextFieldRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataToFilenameCheckbox)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jLabel3.text")); // NOI18N

        jButtonCargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/nbdbdump/resources/open-icon.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButtonCargar, org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jButtonCargar.text")); // NOI18N
        jButtonCargar.setToolTipText(org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jButtonCargar.toolTipText")); // NOI18N
        jButtonCargar.setEnabled(false);
        jButtonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarActionPerformed(evt);
            }
        });

        jButtonRestore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/nbdbdump/resources/restore.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButtonRestore, org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jButtonRestore.text")); // NOI18N
        jButtonRestore.setEnabled(false);
        jButtonRestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestoreActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jLabel5.text")); // NOI18N

        jLabelRutaBackup.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabelRutaBackup, org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jLabelRutaBackup.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabelArchivoBackup, org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jLabelArchivoBackup.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jLabel7.text")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelArchivoBackup, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jButtonCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButtonRestore, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelRutaBackup, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel7)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabelArchivoBackup)))
                    .addComponent(jButtonCargar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelRutaBackup))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRestore, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jPanel3.TabConstraints.tabTitle"), jPanel3); // NOI18N

        jTextFieldComando.setFont(new java.awt.Font("Ubuntu", 0, 8)); // NOI18N
        jTextFieldComando.setText(org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jTextFieldComando.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(mysqldumpPathLabel, org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.mysqldumpPathLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(mysqldumpPathBtn, org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.mysqldumpPathBtn.text")); // NOI18N
        mysqldumpPathBtn.setToolTipText(org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.mysqldumpPathBtn.toolTipText")); // NOI18N
        mysqldumpPathBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mysqldumpPathBtnActionPerformed(evt);
            }
        });

        mysqldumpPathTextField.setText(org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.mysqldumpPathTextField.text")); // NOI18N

        statementsComboBox.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Insert", "Insert with data" }));

        selectedDatabasesTextField.setEditable(false);
        selectedDatabasesTextField.setText(org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.selectedDatabasesTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(statementsLabel, org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.statementsLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(selectedDatabasesLabel, org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.selectedDatabasesLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(okBtn, org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.okBtn.text")); // NOI18N
        okBtn.setEnabled(false);
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jButton1.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mysqldumpPathLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(statementsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectedDatabasesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(selectedDatabasesTextField)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mysqldumpPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mysqldumpPathBtn))
                            .addComponent(statementsComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldComando, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 12, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mysqldumpPathLabel)
                    .addComponent(mysqldumpPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mysqldumpPathBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statementsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statementsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectedDatabasesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectedDatabasesLabel))
                .addGap(7, 7, 7)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldComando, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okBtn)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jTabbedPane2.addTab(org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jLabel8.text")); // NOI18N

        jTextFieldPathMongodb.setText(org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jTextFieldPathMongodb.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel9, org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jLabel9.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel10, org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jLabel10.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel11, org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jLabel11.text")); // NOI18N

        jTextField1.setText(org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jTextField1.text")); // NOI18N

        jTextField2.setText(org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jTextField2.text")); // NOI18N

        jTextField3.setText(org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jTextField3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel12, org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jLabel12.text")); // NOI18N

        jTextField4.setText(org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jTextField4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel13, org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jLabel13.text")); // NOI18N

        jTextField5.setText(org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jTextField5.text")); // NOI18N

        jButtonSelectDirectory1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/nbdbdump/resources/open-icon.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButtonSelectDirectory1, org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jButtonSelectDirectory1.text")); // NOI18N
        jButtonSelectDirectory1.setToolTipText(org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jButtonSelectDirectory1.toolTipText")); // NOI18N
        jButtonSelectDirectory1.setEnabled(false);
        jButtonSelectDirectory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectDirectory1ActionPerformed(evt);
            }
        });

        jButtonBackup1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/nbdbdump/resources/backupgreen.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButtonBackup1, org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jButtonBackup1.text")); // NOI18N
        jButtonBackup1.setEnabled(false);
        jButtonBackup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackup1ActionPerformed(evt);
            }
        });

        jButtonRestore1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/nbdbdump/resources/restore.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButtonRestore1, org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jButtonRestore1.text")); // NOI18N
        jButtonRestore1.setEnabled(false);
        jButtonRestore1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestore1ActionPerformed(evt);
            }
        });

        jButtonSelectDirectory2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/avbravo/nbdbdump/resources/open-icon.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jButtonSelectDirectory2, org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jButtonSelectDirectory2.text")); // NOI18N
        jButtonSelectDirectory2.setToolTipText(org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jButtonSelectDirectory2.toolTipText")); // NOI18N
        jButtonSelectDirectory2.setEnabled(false);
        jButtonSelectDirectory2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectDirectory2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPathMongodb))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSelectDirectory1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSelectDirectory2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11)
                                        .addGap(36, 36, 36)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonBackup1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jTextField3)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonRestore1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(126, Short.MAX_VALUE))))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldPathMongodb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSelectDirectory1)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonBackup1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRestore1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jButtonSelectDirectory2))
                        .addGap(21, 21, 21))))
        );

        jTabbedPane3.addTab(org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jPanel6.TabConstraints.tabTitle"), jPanel6); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab(org.openide.util.NbBundle.getMessage(NbDbDumpDialog.class, "NbDbDumpDialog.jPanel5.TabConstraints.tabTitle"), jPanel5); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelectDirectory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectDirectory1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSelectDirectory1ActionPerformed

    private void jButtonBackup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackup1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackup1ActionPerformed

    private void jButtonRestore1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestore1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRestore1ActionPerformed

    private void jButtonSelectDirectory2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectDirectory2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSelectDirectory2ActionPerformed

    private void jButtonRestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestoreActionPerformed
        try {
            if (dataBase.equals("")) {
                advertencia(NbBundle.getMessage(NbDbDumpDialog.class, "Message_NoDataBase"));
                return;
            }
            if (archivoRestore.equals("") || rutaRestore.equals("")) {
                advertencia(NbBundle.getMessage(NbDbDumpDialog.class, "Message_NoRestoreSelected"));
                return;
            }

            //windows
            //Runtime.getRuntime().exec("C:\\Program Files\\MySQL\\MySQL Server 5.0\\bin\\mysql -u root -p123 example < C:/backup.sql");
            Integer processComplete;

            //String[] executeCmd = new String[]{"mysql ", this.dataBase, "-u" + ConnectionHelper.getUserDB(), "-p" + ConnectionHelper.getPasswordDB(), "-e", " source " + this.rutaRestore};
            //"--host=", this.host,
            String[] executeCmd = new String[]{"mysql", this.dataBase, "-h", this.host, "-u" + ConnectionHelper.getUserDB(), "-p" + ConnectionHelper.getPasswordDB(), "-e", " source " + this.rutaRestore};
            Process runtimeProcess = Runtime.getRuntime().exec(executeCmd);// execute the command
            processComplete = runtimeProcess.waitFor();
            if (processComplete.equals(1)) {
                informacion(NbBundle.getMessage(NbDbDumpDialog.class, "Message_RestoredFailed"));
            } else if (processComplete == 0) {
                {
                    informacion(NbBundle.getMessage(NbDbDumpDialog.class, "Message_Restored"));
                }
            }
        } catch (Exception e) {
            error(e.getLocalizedMessage());
        }
    }//GEN-LAST:event_jButtonRestoreActionPerformed

    private void jButtonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarActionPerformed
        try {
            limpiar();
            final JFileChooser chooser = new JFileChooser();
            chooser.setCurrentDirectory(new java.io.File("."));
            chooser.setDialogTitle("Backup File");
            chooser.setAcceptAllFileFilterUsed(false);
            FileNameExtensionFilter filter = new FileNameExtensionFilter("Script", "sql");
            chooser.setFileFilter(filter);
            if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
                archivoRestore = chooser.getSelectedFile().getName();
                rutaRestore = chooser.getSelectedFile().getAbsolutePath();
                jLabelArchivoBackup.setText(archivoRestore);
                jLabelRutaBackup.setText(rutaRestore);
                jButtonRestore.setEnabled(true);
            } else {
                advertencia(NbBundle.getMessage(NbDbDumpDialog.class, "Message_NoFileSQL"));
            }
        } catch (Exception e) {
            error(e.getLocalizedMessage());
        }
    }//GEN-LAST:event_jButtonCargarActionPerformed

    private void dataToFilenameCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataToFilenameCheckboxActionPerformed
        try {
            java.util.Calendar ca = java.util.Calendar.getInstance();
            java.sql.Date mydate = new java.sql.Date(ca.getTimeInMillis());

            this.Anio = ca.get(java.util.Calendar.YEAR);
            this.Mes = ca.get(java.util.Calendar.MONTH);
            //ya que el mes lo pone en cero
            this.Mes++;

            this.Dia = ca.get(java.util.Calendar.DAY_OF_MONTH);
            this.hours = ca.get(java.util.Calendar.HOUR_OF_DAY);
            this.min = ca.get(java.util.Calendar.MINUTE);
            this.seconds = ca.get(java.util.Calendar.SECOND);
//            String backupFileName = jLabelDataBases.getText() + String.valueOf(this.Anio);
            String backupFileName = "TestName";
//            if (this.Mes < 10) {
//                archivo += "0" + String.valueOf(this.Mes);
//            } else {
//                archivo += String.valueOf(this.Mes);
//            }
//            if (this.Dia < 10) {
//                archivo += "0" + String.valueOf(this.Dia);
//            } else {
//                archivo += String.valueOf(this.Dia);
//            }
//            if (this.hours < 10) {
//                archivo += "0" + String.valueOf(this.hours);
//            } else {
//                archivo += String.valueOf(this.hours);
//            }
//            if (this.min < 10) {
//                archivo += "0" + String.valueOf(this.min);
//            } else {
//                archivo += String.valueOf(this.min);
//            }

            backupFileName += ".sql";
        } catch (Exception e) {
            error(e.getLocalizedMessage());
        }
    }//GEN-LAST:event_dataToFilenameCheckboxActionPerformed

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        try {
            String outputCommand = "";
            //String comando = "mysqldump --host=" + this.host + " --opt --user=" + ConnectionHelper.getUserDB() + " --password=" + ConnectionHelper.getPasswordDB() + " --add-drop-table " + this.dataBase + "  -r  " + jTextFieldRuta.getText() + jLabelDataBases.getText() + ".sql";
            //            if (osName.toLowerCase().equals("windows")) {
                //
                //            } else {
                //                outputCommand = "mysqldump --host=" + this.host + " --opt --user=" + ConnectionHelper.getUserDB() + " --password=" + ConnectionHelper.getPasswordDB() + " --add-drop-table " + this.dataBase + "  -r  " + jTextFieldRuta.getText() + jLabelNameBackup.getText();
                outputCommand = "mysqldump --host=" + this.host + " --opt --user=" + ConnectionHelper.getUserDB() + " --password=" + ConnectionHelper.getPasswordDB() + " --add-drop-table " + this.dataBase + "  -r  " + jTextFieldRuta.getText();
                //            }

            jTextFieldComando.setText(outputCommand);
            //windows
            //            String varname="cmd mysqldump -uroot -ppassword databasename>c:\\backup.sql"
            //Runtime.getRuntime().exec(varname);
            Process proc = Runtime.getRuntime().exec(outputCommand);
            if (proc.getErrorStream() == null) {
                advertencia("error backup");
                return;
            }
            //Guarda la ruta del backup
            NbPreferences.forModule(NbDbDumpOptionsPanel.class).put("pathbackupfolder", jTextFieldRuta.getText());

            informacion(NbBundle.getMessage(NbDbDumpDialog.class, "Message_Backup"));
        } catch (IOException e) {
            error(e.getLocalizedMessage());
        } catch (MissingResourceException e) {
            error(e.getLocalizedMessage());
        }
    }//GEN-LAST:event_okBtnActionPerformed

    private void jButtonSelectDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectDirectoryActionPerformed
//        try {
//            limpiar();
//            //            String osName = System.getProperty("os.name");
//            final JFileChooser chooser = new JFileChooser();
//            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
//            chooser.setAcceptAllFileFilterUsed(false);
//            if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
//                String ruta = chooser.getSelectedFile().toString();
//                ruta = ruta.replaceFirst("/./", "/");
//
//                if (osName.equals("linux")) {
//                    jTextFieldRuta.setText(ruta);
//                } else {
//                    //                 ruta = ruta.replaceAll("\", '\\');"
//                        String colores = ruta;
//                        String[] arrayColores = ruta.split("\\");
//
//                            // En este momento tenemos un array en el que cada elemento es un color.
//                            for (String arrayColore : arrayColores) {
//                                System.out.println(arrayColore);
//                            }
//
//                        }
//
//                        //                        jLabelNameBackup.setText(jLabelDataBases.getText() + ".sql");
//                        jButtonBackup.setEnabled(true);
//                    } else {
//                        informacion(NbBundle.getMessage(NbDbDumpDialog.class, "Message_NoDirectory"));
//                    }
//                } catch (HeadlessException e) {
//                    error(e.getLocalizedMessage());
//                } catch (MissingResourceException e) {
//                    error(e.getLocalizedMessage());
//                }
    }//GEN-LAST:event_jButtonSelectDirectoryActionPerformed

    private void jTextFieldRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRutaActionPerformed

    private void mysqldumpPathBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mysqldumpPathBtnActionPerformed
//        try {
//            osName = osName.toLowerCase();
//            final JFileChooser chooser = new JFileChooser();
//            //            chooser.setCurrentDirectory(new java.io.File("."));
//            //            chooser.setDialogTitle("Directory");
//            //            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
//            //            chooser.setAcceptAllFileFilterUsed(false);
//
//            if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
//                String pathOfExecutable = chooser.getSelectedFile().toString();
//                mysqldumpPathTextField.setText(pathOfExecutable);
//            }
//        } catch (HeadlessException e) {
//            printStackTrace(e.getLocalizedMessage());
//        }
    }//GEN-LAST:event_mysqldumpPathBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox dataToFilenameCheckbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBackup1;
    private javax.swing.JButton jButtonCargar;
    private javax.swing.JButton jButtonRestore;
    private javax.swing.JButton jButtonRestore1;
    private javax.swing.JButton jButtonSelectDirectory;
    private javax.swing.JButton jButtonSelectDirectory1;
    private javax.swing.JButton jButtonSelectDirectory2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelArchivoBackup;
    private javax.swing.JLabel jLabelRutaBackup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextFieldComando;
    private javax.swing.JTextField jTextFieldPathMongodb;
    private javax.swing.JTextField jTextFieldRuta;
    private javax.swing.JButton mysqldumpPathBtn;
    private javax.swing.JLabel mysqldumpPathLabel;
    private javax.swing.JTextField mysqldumpPathTextField;
    private javax.swing.JButton okBtn;
    private javax.swing.JLabel selectedDatabasesLabel;
    private javax.swing.JTextField selectedDatabasesTextField;
    private javax.swing.JComboBox<String> statementsComboBox;
    private javax.swing.JLabel statementsLabel;
    // End of variables declaration//GEN-END:variables

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    public void informacion(String msg) {
        try {
            nd = new NotifyDescriptor.Message(msg, NotifyDescriptor.Message.INFORMATION_MESSAGE);
            DialogDisplayer.getDefault().notify(nd);
        } catch (Exception ex) {
            nd = new NotifyDescriptor.Message("Informacion() " + ex.getLocalizedMessage(), NotifyDescriptor.Message.ERROR_MESSAGE);
            DialogDisplayer.getDefault().notify(nd);
        }
    }
    /*
     * Mensaje Advertencia
     */

    public void advertencia(String msg) {
        try {
            nd = new NotifyDescriptor.Message(msg, NotifyDescriptor.Message.WARNING_MESSAGE);
            DialogDisplayer.getDefault().notify(nd);
        } catch (Exception ex) {
            nd = new NotifyDescriptor.Message("Advertencia() " + ex.getLocalizedMessage(), NotifyDescriptor.Message.ERROR_MESSAGE);
            DialogDisplayer.getDefault().notify(nd);
        }
    }
    /*
     * Mensaje Error
     */

    public void error(String msg) {
        try {
            nd = new NotifyDescriptor.Message(msg, NotifyDescriptor.Message.ERROR_MESSAGE);
            DialogDisplayer.getDefault().notify(nd);
        } catch (Exception ex) {
            nd = new NotifyDescriptor.Message("Error() " + ex.getLocalizedMessage(), NotifyDescriptor.Message.ERROR_MESSAGE);
            DialogDisplayer.getDefault().notify(nd);
        }
    }

    private void limpiar() {
        archivoBackup = "";
        rutaBackup = "";
        archivoRestore = "";
        rutaRestore = "";
        jTextFieldComando.setText("");
        okBtn.setEnabled(false);
        jButtonRestore.setEnabled(false);
    }
}
