package org.avbravo.dbackrestore;

import java.awt.HeadlessException;
import javax.swing.JFileChooser;
import static jdk.nashorn.internal.objects.NativeError.printStackTrace;
import org.openide.util.NbPreferences;

final class DBackupRestoreOptionsPanel extends javax.swing.JPanel {
    private final DBackupRestoreOptionsOptionsPanelController controller;
    private String osName = System.getProperty("os.name").toLowerCase();

    DBackupRestoreOptionsPanel(DBackupRestoreOptionsOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        mysqldumpPathTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(DBackupRestoreOptionsPanel.class, "DBackupRestoreOptionsPanel.jLabel2.text")); // NOI18N

        mysqldumpPathTextField.setText(org.openide.util.NbBundle.getMessage(DBackupRestoreOptionsPanel.class, "DBackupRestoreOptionsPanel.mysqldumpPathTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(DBackupRestoreOptionsPanel.class, "DBackupRestoreOptionsPanel.jButton1.text")); // NOI18N
        jButton1.setToolTipText(org.openide.util.NbBundle.getMessage(DBackupRestoreOptionsPanel.class, "DBackupRestoreOptionsPanel.jButton1.toolTipText")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mysqldumpPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mysqldumpPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            osName = osName.toLowerCase();
            final JFileChooser chooser = new JFileChooser();
//            chooser.setCurrentDirectory(new java.io.File("."));
//            chooser.setDialogTitle("Directory");
//            chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
//            chooser.setAcceptAllFileFilterUsed(false);

            if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
                String pathOfExecutable = chooser.getSelectedFile().toString();
                mysqldumpPathTextField.setText(pathOfExecutable);
            }
        } catch (HeadlessException e) {
            printStackTrace(e.getLocalizedMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    void load() {
        // TODO read settings and initialize GUI
        // Example:
        // someCheckBox.setSelected(NbPreferences.forModule(DBackupRestoreOptionsPanel.class).getBoolean("someFlag", false));
        mysqldumpPathTextField.setText(NbPreferences.forModule(DBackupRestoreOptionsPanel.class).get("mysqldump.path", ""));

    }

    void store() {
        // Example:
        // NbPreferences.forModule(DBackupRestoreOptionsPanel.class).putBoolean("someFlag", someCheckBox.isSelected());
        NbPreferences.forModule(DBackupRestoreOptionsPanel.class).put("mysqldump.path", mysqldumpPathTextField.getText());
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mysqldumpPathTextField;
    // End of variables declaration//GEN-END:variables
}
